### ISSUE TITLE
[WIP] Store Roadmap

### ISSUE THREAD

**Issue by kaiserd** [waku-org/nwaku#1024]
# Waku Store Roadmap

> ⚠️  **NOTE:** Work in progress. This issue is incomplete and will be edited.

This issue tracks tasks related to our roadmap for the message store.

The goal is for the message store to evolve from offering the functionality the store protocol needs to an efficient production-grade implementation.

### TODO
- [ ] #1159
- [x] #1292
- [ ] store: document waku store's grafana dashboard based troubleshooting
- [ ] store: limit max concurrent history queries handled by a store node
- [ ] store: SQLite message store common queries prepared statements

### DONE
- [x] #1103
- [x] #1155
  	* #1169 
- [x] #1026
- [x] Remove VACCUM on insertion
	* #1025 
- [x] Store interface that abstracts from concrete store implementations
	* #1043
	* #1070 
	* #1141
	* #1147
	* #1163 
	* #1165
	* #1164 
	* #1167 

### Backlog/Performance Improvements

* Investigate the blocking issue mentioned in #982
* Move from the three-column primary key `(senderTimestamp, id, pubsubTopic)` to a single-column primary key that binary encodes `(senderTimestamp, id, pubsubTopic)`.
* Add more indexes (also backward index)
* ~make  `--sqlite-retention-time` a duration, so that it the retention time can be specified in days and other time units besides seconds.~ Moved to #1103
* Investigate an in-memory cache for the SQLite store
  - Since the Waku message store does not need the relational property of SQL, we should investigate [Redis](https://redis.io/) (and other efficient key-value stores) as an alternative
  - A persistence layer can be added
  - Losing a small number of messages should be acceptable if we gain a significant performance boost
    - Such losses are expected to be rare, if they even occur...
- [ ] #1154

**Comment by jm-clius** [comment]
Excellent roadmap. Thanks @kaiserd. @LNSD may get involved here.

cc @iurimatias @richard-ramos

**Comment by richard-ramos** [comment]
A possible improvement for sqlite could be to execute this pragma on init:
```
pragma temp_store = memory;
```
Depending on the query execution plan, it might improve performance as temporary tables and indices would be kept in memory.

**Comment by LNSD** [comment]
I am taking over #1026

**Comment by D4nte** [comment]
What about being able to configure the store limit in days instead of number of messages?

**Comment by kaiserd** [comment]
For now, I added a retention time option to be specified in seconds: #982
I did not use a duration, which woulud allow specifying in hours/days,  because nim confutils does not support durations, and the PR should be merged asap.
Ill add the making `--sqlite-retention-time` a duration to the roadmap.

**Comment by rymnc** [comment]
Brought from a discussion with @jm-clius -

For alternatives to Redis, we can use - 
1. RocksDB - implementation in [nim](https://github.com/status-im/nim-rocksdb)
2. ParityDB - *extension* of RocksDB, but with constant reads - https://github.com/paritytech/parity-db/issues/82 - would require further discussion
3. LMDB - Has transactional capabilities, would we need them in the future? - implementation in [nim](https://github.com/FedericoCeratto/nim-lmdb)

RocksDB and LMDB have been used in [nim-eth](https://github.com/status-im/nim-eth) [here](https://github.com/status-im/nim-eth/tree/3ee5651b7c1b967e9aa115d99125ed35ac3ab2f1/eth/trie/backends)

I believe some work has been done on implementing a generic store interface, so it could be possible to have a PoC with some alternatives.

We could adapt their usage, if we had some metrics on -
1. reads vs writes on waku
2. median message size

cc: @LNSD

**Comment by rymnc** [comment]
Tracking the concept of having messages with a time-to-live here too -
There has been some considerable discussion revolving around using a `ttl` vs `ephemeral` field, and consensus was called  on using the `ephemeral` field.

Relevant comments: 
- https://github.com/vacp2p/rfc/pull/532#issuecomment-1239413675
- https://github.com/vacp2p/rfc/pull/532#issuecomment-1240512609

Relevant commits:
- [6e31e45](https://github.com/vacp2p/rfc/pull/532/commits/6e31e450fcc894f95ee0b1df09d193e662604962)
- [d1f6023](https://github.com/status-im/nwaku/pull/1119/commits/d1f60238aeb04cac93892e84c93bf1845fdd91f3)

**Comment by LNSD** [comment]
As always, it depends on our use cases and the performance requirements that we have. Once we have clearly defined use cases and requirements, we can start thinking of the evolution of the current store.

IMHO it is not the moment to switch technologies. At the current load, SQLite can perform reasonably well.

If we want another persistence solution, the natural movement would be to use an external SQL database server (most of the queries and part of the logic could be reused).

Going for a no-SQL solution is something, IMO, that we cannot afford at this moment. It is a complete change of the DB technology, and it would require a relatively big effort to port part of the "business logic" to another DB technology.

Before changing the DB technology, I think there are plenty of solutions to explore, with their pros and cons. It depends on the problem: For example:
* For insertion performance issues, buffering messages in memory and then inserting them could be one solution. 
* For query performance problems, usually a "smart cache" mechanism (better than SQLite's cache) is typically used (typically built on Redis).
* If the bottleneck is that a node cannot cope with a large number of queries, maybe we need to start doing some kind of rate limiting at the fleet nodes, and queries with timeout on the client side will change the node and retry if the request times out. 
* If we go with an external server, we can play with node specialization (writers and readers).

And don't forget that in a decentralized network world, we should also provide an embedded database technology to ease the adoption (less and opinionated configuration usually translates into larger adoption).

**Comment by fryorcraken** [comment]
# 15 Oct

## Attendees

- @richard-ramos 
- @LNSD 
- @fryorcraken 

## Minutes

General optimization of Store implementation by studying Status Communities usage.

From Grafana, peak queries (30s) are related to queries with 100+ content topics (158) with page size of 1000 (limited to 100).

Status Communities query types:

1. Community description: single content topic, latest message only
2. User contact, user status (for 1:1 chats): one content topic per user, latest message only for each type.
3. Channel's messages: one content topic per channel, as many messages as possible
4. User status (for community chats): one content topic per community, latest message only

Some considerations:
a. There are several cases (user status, contact) where the only the latest message is interesting.
b. Other cases, the first page per content topic is most import for UX (chat messages)

### Functional optimization review

#### Latest message

In the cases where only the latest message is needed, then a query with a single content topic and a page size of 1 would be more performant that batching of content topics.

For this, the current designs are needed:

- Being able to stop pagination after the first page is received: not available in go-waku
- Application sends one type of message per content topic:
	- Currently is the case for community description
	- However, user contact and user status for 1:1 msgs are sent under same content topic

#### Latest message(s)

In the case of retrieval of channel messages: The first page of messages **per channel** seems the most important: so user can see all messages that can fit in the screen one opening chat (let's say 50)

#### Generalization

Currently, it seems that one store query is done to retrieve **all** information:

- Chat messages
- User status
- User contact

Which leads to some under optimization:

- Retrieval of unneeded messages (ie, out of date user status, user contact or community description)
- Most important messages (latest 50 messages per channel) are not prioritized: all messages for all channels are queried at the same time, meaning that it may take several page requests to get the latest 50 messages for a given channel)

The generalized model is that **for a given content topic**, either:
- only the latest message is needed
- The most recent X (e.g. 50) messages are needed first (to display to user).

#### Proposal

**Client side**:

Split the queries per content topics:

a. Query of page size 1, backward direction, for given community description (only latest matter), stop when first page is received
b. Query of page size 1, backward direction, for user contact (only latest matter): This would mean changing Status' behaviour to send user contact on a separate content topic from user channel
c. Query of page size X, backward direction, for given chat (1 content topic), so that the X latest messages are received first to display to user (pagination can continue).

Set user Status as ephemeral: User status messages are sent every 5min and only latest status is necessary. A 1% optimization would be to mark this message as ephemeral. One could also increase the frequency to reduce the time period during which the user's status is unknown.

**Server side**:
Limit the number of content topic per store queries: larger the set of content topic, more complex and slower the query.

#### Other considerations

SQLite does not support parallel queries, hence, from a client perspective, smaller queries should be prioritized (e.g. 1 msg needed) and most important query in term of UX too (e.g page open by user?)

Sending several queries instead of one has some caveats:
- multiple messages over the stream: How does this play with mplex vs yamux? Would migration to yamux help this scenario?
- Reduce privacy criteria? Instead of 1 query with many content topic, we have individual queries with one content topics, does this change anything?

Possible protocol improvement to solve this caveats would be a batch query, e.g.:

- do one network request that contains several query history: this enables different time and page size per content topic
- stream query responses back as the queries are resolved.

**Comment by fryorcraken** [comment]
TODO: We need to ensure that the proposed queries would match a SQLite prepared statement.

**Comment by fryorcraken** [comment]
# 15 Oct (afternoon)

## attendees

- @richard-ramos 
- @LNSD 
- @felicio 
- @prichodko 
- @fryorcraken 

## minutes
nvesti
### Feedback on morning session (store performance)

- latest message in DB may not be the most up to date message (e.g. 2 admin node for one community).
- latest message in DB, may not be relevant (garbage on the content topic).
- would still be relevant, most as a "soft latest message" system. ie, page of 10, no end time/start time, check message received and stop when valid message is received. 
- Users send contact details on unique content topic only, meaning to retrieve contact details, query on as many content topics as users need to be done (eg 100 etc)
	- 1 option would be, similarly to retrieve latest messages, retrieve contact details of online users first (online status present in community content topic), and then paginate
	- another option would be to send the contact details on the community content topic
- Waku teams need to better understand what are page size make sense for Status to optimize for first page retrieval and hence provide smooth UX.
 - e.g. How many messages can be displayed max in the UI (before scrolling) 50? 100?
 - e..g How many contact details, ie, content topic, would be enough to display online user in side bar. 10? 20?
 - Usage of start time/end time: not really needed for a client app, this is for a service node.
- Usage should be with cursor and no time. Going backward direction and having a way to stop pagination once "enough" messages (from app pov) are received. If more messages are needed, then cursor query is done.
- [ ] js-waku to implement cursor https://github.com/waku-org/js-waku/issues/964
- [ ] js-waku to reduce visibility of start/end time

### Filter Relay Light Push

- Filter is in alpha and we already know that we want to do some improvements around:
  - Having a ACK when subscribing
  - Better handle when connection drop on alive subscriptions
  - Switching from relay to filter + light push does not change privacy guarantees as long as Waku store is used
  - More private solutions can be reviewed in the fuutre (ie, putting tor or nym between client and store)

### Investigation tool

- May be useful to have alerts on Grafana re response time
	- This can be done once feedback above in query usage is implemented on Status side (pending some js-waku and go-waku API change) and a second round of dogfooding is done to confirm no more slow queries.
	- @LNSD to write guide on how to use Grafana + Kibana

### Key Management

- Sharing profiles cross devices on Status Web
- Right now: temporary profiles (keys in browser)
- @prichodko to organize call with @fryorcraken and @cammellos to talk about device pairing and how web could fit in there
- @fryorcraken to talk with Vac re long term identities and encryption (e.g zk, etc)

**Comment by fryorcraken** [comment]
Also, someone on Status Client side needs to confirm what page size makes sense:
- When retrieving messages (ie, what is the max number of messages that can be displayed to a user before scrolling)
- When retrieving community description (to find the most recent valid description)
- When retrieving user status/user details (how many users are displayed in the side bar before scrolling)

@prichodko as we discussed this, are you happy to follow up with client team and get us some answers?

**Comment by richard-ramos** [comment]
The following issues were created to track go-waku/status-go changes required to improve store performance
- https://github.com/status-im/go-waku/issues/354
- https://github.com/status-im/go-waku/issues/353
- https://github.com/status-im/status-go/issues/2929
- https://github.com/status-im/status-go/issues/2930

**Comment by jm-clius** [comment]
@LNSD although this issue contains some important past discussions and direction, I think the value of keeping it open has diminished over time, especially given the current focus on postgresql. If you agree that we have visibility of outstanding items elsewhere, feel free to close.

**Comment by LNSD** [comment]
I think we can close it 😁✅
