### ISSUE TITLE
[Epic] complete/update Noise module implementation

### ISSUE THREAD

**Issue by s1fr0** [waku-org/nwaku#1064]
## Problem

The current implementation of the Noise module lacks some features contemplated by its corresponding RFC [35/WAKU2-NOISE](https://rfc.vac.dev/spec/35/).

## Scope

Reduce metadata leakages when exchanging encrypted messages. Align implementation to specifications by implementing missing features.

List of issues/PRs:
- [x] https://github.com/status-im/nwaku/pull/979
- [x] https://github.com/status-im/nwaku/issues/936
- [x] https://github.com/status-im/nwaku/issues/1063
- [ ] Upgrade [35/WAKU2-NOISE](https://rfc.vac.dev/spec/35/) from RAW to DRAFT

## Acceptance criteria

Issues/PRs defined in scope addressed/merged.

## Out of scope

Implementation of after-handshake logic. This will become clear with the development and implementation of [37/WAKU2-NOISE-SESSIONS](https://rfc.vac.dev/spec/37/) tracked in https://github.com/status-im/nwaku/issues/1052.

## Future steps

Possible follow-ups include adding support to `Blake2b` as symmetric primitive and `Curve448` as DH elliptic curve, that is address the optional tasks of https://github.com/status-im/nwaku/issues/881.

**Comment by oskarth** [comment]
> The current implementation of the Noise module lacks some features contemplated by its corresponding RFC [35/WAKU2-NOISE](https://rfc.vac.dev/spec/35/).

This isn't the actual problem :) What is the problem we are solving for users? What is the capability we are unlocking that @fryorcraken will be able to sell to users?

Also probably needs "spec to draft" issue, currently spec is raw. Is it accurate that addressing these issues will make spec draft?

Other than that scope looks good I think

**Comment by oskarth** [comment]
Ping on above comment @s1fr0 

I take this issue as being something that will come after https://github.com/status-im/nwaku/issues/1065 but isn't being actively worked on now

**Comment by fryorcraken** [comment]
We had some discussion with @s1fr0 already regarding how noise-session can be useful.

One of the first "internal" use case would be to exchange WebRTC signal data over the waku network in a secure manner so that 2 browser (or other webrtc compatible) peers can connect to each other directly.
