### ISSUE TITLE
Milestone: securely transfer Noise sessions

### ISSUE THREAD

**Issue by s1fr0** [waku-org/nwaku#1065]
## Problem

At the end of a successful Noise handshake, each party will compute on their respective device some cryptographic material which is used to secure their future communications. Since the encryption keys will be stored on the devices that executed the handshake, the communication could happen only between such devices.

## Scope

With the final goal to implement multi-devices communications, we need to design a mechanism to securely exchange (cryptographic) information between 2 or more devices possessed by a user.

List of issues:
- [x] https://github.com/vacp2p/research/issues/130. Solution to this issue required specifically addressing https://github.com/status-im/nwaku/issues/1081 on which depends https://github.com/vacp2p/research/issues/131
- [x] Propose an RFC: https://github.com/vacp2p/rfc/pull/531
- [x] Implement the design agreed in previous point https://github.com/status-im/nwaku/pull/1117

## Acceptance criteria

Issues defined in scope addressed.

## Out of scope

Synced multi-device n-to-m communications between Alice and Bob.

**Comment by oskarth** [comment]
I think this milestone as being something you are working on right now @s1fr0
