### ISSUE TITLE
[Epic] add support to multi-devices communications

### ISSUE THREAD

**Issue by s1fr0** [waku-org/nwaku#1066]
## Problem
On successful execution of a Noise handshake, Alice and Bob will share some cryptographic key material that is used to encrypt their communication. Once https://github.com/status-im/nwaku/issues/1065 is completed, Alice and Bob will be able to transfer this or new cryptographic material among the devices in their possession. However, they will not be able to send and receive messages from any of their devices. 

## Scope

Add support to multi-device communication, that is Alice and Bob can securely send and receive messages from any of their devices. This effectively complete the implementation of [37/WAKU2-NOISE-SESSIONS](https://rfc.vac.dev/spec/37/).

List of issues:
- [x] https://github.com/vacp2p/research/issues/131 (analysis depends on solution identified in https://github.com/status-im/nwaku/issues/1081)
- [ ] Implement the [NM session management](https://rfc.vac.dev/spec/37/#the-nm-session-management-mechanism) mechanism
- [ ] Implement the [N11M session management](https://rfc.vac.dev/spec/37/#the-n11m-session-management-mechanism) mechanism

## Risks and uncertainty

Message synchronization (and subsequent key material update on all devices) might not be trivial and hard to timely detect for the N11M mechanism. Then communication complexity of the NM mechanism scales quadratically in the number of devices.

## Acceptance criteria

Issues defined in scope addressed.

## Notes and links

In a initial stage of this issue, we might prioritize the implementation of the NM and N11M mechanism over the impact analysis of frequently changing `contentTopic` as per [37/WAKU2-NOISE-SESSIONS](https://rfc.vac.dev/spec/37/) . In such case, we can initially implement multi-device communications so that happen all over the same `contentTopic` (this will impact user's anonymity) and later analyze/implement a `contentTopic` change logic.

This milestone is blocked by https://github.com/status-im/nwaku/issues/1065.
