### ISSUE TITLE
HTTP REST API: Store, Filter, Lightpush, Admin and Private APIs

### ISSUE THREAD

**Issue by jm-clius** [waku-org/nwaku#1076]
**Planned start date**:
**Due date**:

# Summary

We've previously added [a basic HTTP REST API](https://github.com/status-im/nwaku/issues/727) for `nwaku`, covering Relay and Debug functionality. This issue tracks the effort to add basic Store, Filter, Admin and Private HTTP REST API functionality.

# Acceptance Criteria

- An HTTP REST API for Waku v2 translated directly from the existing JSON-RPC REST API.
  + [x] Store REST API
  + [x] Filter REST API: 
    - https://github.com/status-im/nwaku/pull/1096
    - https://github.com/waku-org/nwaku/issues/1851
    - https://github.com/waku-org/nwaku/issues/1872
  + [x] Health REST API
  + [x] Lightpush REST API
  + [x] Admin REST API
  + [ ] Private REST API

## Tasks
  - [x] https://github.com/waku-org/nwaku/issues/1851
  - [x] https://github.com/waku-org/nwaku/issues/1872
  - [x] https://github.com/waku-org/nwaku/issues/1909 - Added for RLN support of Relay Rest Api
  - [x] https://github.com/waku-org/nwaku/issues/1988 - Health api 
  - [x] https://github.com/waku-org/nwaku/issues/2040
  - [x] https://github.com/waku-org/nwaku/issues/2075
  - [ ] https://github.com/waku-org/nwaku/issues/2120
  - [ ] https://github.com/waku-org/nwaku/issues/2121

# RAID (Risks, Assumptions, Issues and Dependencies)

**Comment by jm-clius** [comment]
Note the issue raised in https://github.com/status-im/nwaku/issues/1032 when implementing the Admin API.

**Comment by NagyZoltanPeter** [comment]
achieved: Legacy Filter - v1 - interface Rest Api support added.
next: Extend Rest Api interface for new v2 filter. Get v2 filter service supported from node.
blocker: -

**Comment by NagyZoltanPeter** [comment]
**Weekly Update**

- _achieved_: Legacy Filter - v1 - interface Rest Api support added.
- _next_: Extend Rest Api interface for new v2 filter. Get v2 filter service supported from node. Add more tests.

**Comment by NagyZoltanPeter** [comment]
**Weekly Update**

- _achieved_: Legacy Filter - v1 - interface Rest Api support added. V2 implementation done wait for PR review
- _next_: Testing and add even more tests for failure cases.

**Comment by NagyZoltanPeter** [comment]
**Weekly Update**

- _achieved_: Legacy Filter - v1 - interface Rest Api support added. V2 implementation done wait for PR review
- _next_: Finish rebase to master, manual adapt of autoshard feature into Filter v2.

**Comment by NagyZoltanPeter** [comment]
**Weekly Update**

- _achieved_: Legacy Filter - v1 - interface Rest Api support added. V2 implementation done wait for PR review
- _next_: Complete Filter v2 PR foundings fixes.
- _blocking_: PR review found a design flow, need a little redesign.

**Comment by NagyZoltanPeter** [comment]
**Weekly Update**

- _achieved_: Legacy Filter - v1 - interface Rest Api support added. V2 implementation done wait for PR review, /health rest api added to check (currently) RLN readiness
- _next_: Last round of Filter v2 PR review with finalized re-worked push handler part.
- _blocking_: /health endpoint come in and Filter v2 work was down prio till.

**Comment by NagyZoltanPeter** [comment]
This conver issue is part of supporting multiple platforms epic, but as being most of its target achieved and already included in current releases (since v0.21.1) I close this issue as is with documented achievements.
Will create a new issue under the same epic to track missing parts (basically /private api only). All other enhancements and bug fixes shall be tracked individually.
