### ISSUE TITLE
chore: address operator trial feedback - laundry list of suggested `nwaku` improvements

### ISSUE THREAD

**Issue by jm-clius** [waku-org/nwaku#1208]
### Background

We recently recently launched a Waku [operator trial](https://github.com/status-im/nwaku/issues/828), where core contributors and community volunteers configure and run their own nwaku nodes and provide feedback about their experiences.

This issue serves as a "catch all" for suggestions and issues raised during the trial (both from operators and our own findings). More substantial suggestions are reported in separate issues.

#### Most voted:

- [x] Docker guide. Tracked in separate issue here: https://github.com/status-im/nwaku/issues/1207
- [x] Simplified config/config file example: https://github.com/status-im/nwaku/issues/1198

#### Laundry list:

- [x] Discv5 reporting (e.g. "discovered node count") should distinguish between bootstrap peers vs external nodes actually discovered via discv5
- [x] Add a guide on how to configure nwaku for use with a VPN + port forwarding (specifically Mullvad, Wireguard)
- [x] Simplify static resource management (https://github.com/status-im/nwaku/issues/798)
- [ ] Guide should include REST commands that people can use to do basic health checks

**Comment by alrevuelta** [comment]
Extending on `Discv5 reporting (e.g. "discovered node count") should distinguish between bootstrap peers vs external nodes actually discovered via discv5` I would relate it to #622. If we add a `source` field for each peer in the peerstore with [discv5, bootstrap, ...] we can get this information from there.

Also related #1354 to that.

**Comment by SionoiS** [comment]
> #### Laundry list:
> * [ ]  Add a guide on how to configure nwaku for use with a VPN + port forwarding (specifically Mullvad, Wireguard)
> * [ ]  Simplify static resource management ([`nim-waku` external files and resources #798](https://github.com/waku-org/nwaku/issues/798))
> * [ ]  Guide should include REST commands that people can use to do basic health checks

@LordGhostX Would that be useful?

**Comment by LordGhostX** [comment]
> > #### Laundry list:
> > 
> > * [ ]   Add a guide on how to configure nwaku for use with a VPN + port forwarding (specifically Mullvad, Wireguard)
> > * [ ]   Simplify static resource management ([`nim-waku` external files and resources #798](https://github.com/waku-org/nwaku/issues/798))
> > * [ ]   Guide should include REST commands that people can use to do basic health checks
> 
> @LordGhostX Would that be useful?

@SionoiS Yup, I'll add these under my radar too 👍

**Comment by Ivansete-status** [comment]
Hey @jm-clius !
Do you think we should keep this opened? It seems as if all the related tasks are closed already

**Comment by Ivansete-status** [comment]
> Let's close!

Thanks for confirmation @jm-clius !
