### ISSUE TITLE
feat(networking): create slots in PeerManager for px/store/lp/filter peers

### ISSUE THREAD

**Issue by alrevuelta** [waku-org/nwaku#1461]
### Problem

We currently have a set of cli flags that enable us to hardcode some specific bootstrap peers such as:
* `--peer-exchange-node`
* `--lightpushnode`
* `--filternode`
* `--storenode`
* `--staticnode`

However these peers are just added to the PeerStore, and once there, they are not differenciated in any way. Meaning that its not guaranteed that eg the provided `storenode` will be used for store queries. This happens because `selectPeer` just fetches a peer with some given capabilities, but it can be any among the existing ones in the peerstore.

### Suggested solution
Define some "slots" in the PeerManager/PeerStore that store each one of these peers: px/lp/filter/store and that are populated at startup with the desired nodes. So whenever we try to get `selectPeer(WakuStoreCodec)` we get the specified one. As a nice to have we can have a fallback mechanisim if the "slot node" is not available.

Note that imho the end goal is to remove all these flags and just provide a set of bootstrap nodes, without differenciating them. Then, whenever we want to interact with a node supporting xxx codec, we let the peermanger select the best one for us. But thats beyond this issue.

### Acceptance criteria

- [ ] Defined slots for px/lp/filter/store peers in the PeerStore/Manager, populated via the setXXXNode methods.
- [ ] Nodes in these slots are used as default when selectPeer(WakuXXXCodec)
- [ ] It fallbacks to another node if the bootsrap is not available.

### Tasks:

- [ ] Refactor `setStorePeer`, `setFilterPeer` etc to `addServicePeer(peer, codec)` and add them to the slots present in the peer store.
- [ ] Remove codec from `addPeer` since all peers are `WakuRelayCodec`. Service peers are handled by `addServicePeer`.
- [ ] Move `selectPeer` to `peer_manager` and treat service peers different than relay peers.
- [ ] #1477

cc @jm-clius @LNSD

**Comment by alrevuelta** [comment]
Closed in https://github.com/waku-org/nwaku/pull/1473
