### ISSUE TITLE
chore(archive): allow request concurrency towards PostgreSQL

### ISSUE THREAD

**Issue by jm-clius** [waku-org/nwaku#1604]
In order to allow for a scalable and fault-resistant Waku Archive technology as set out in https://github.com/waku-org/pm/issues/12, we have decided to implement a PostgreSQL backend.

Work on adding basic support for PostgreSQL has started: https://github.com/waku-org/nwaku/pull/1590

A related work item, required for scalability, is to allow processing store requests concurrently. The standard library integration will, similar to the previous SQLite-based implementation, block on processing a store query, which is not scalable at high store query rates.

A simple solution may be to adapt https://github.com/treeform/pg to work with `nim-chronos`, i.e. an async wrapper functioning as an extension of the std library API. 

cc @cammellos @LNSD

## Tasks
- [x] Allow to put and retrieve messages from PostgreSQL database.
- [x] Make sure the interaction with the PostgreSQL is asynchronous.
- [x] Implement the whole "waku archive" through the postgresql driver.
- [x] Add the config option to allow wakunode2 interact with postgres database instead of sqlite.
- ~~[ ] Keep the sql queries in external .sql plain text files ( [comment](https://github.com/waku-org/nwaku/pull/1764#discussion_r1209926160) ) . Also, important to pay attention to the @LNSD comment: https://github.com/waku-org/nwaku/pull/1590#discussion_r1130889349~~ -> created a separate [issue](https://github.com/waku-org/nwaku/issues/1841)
- ~~[ ] Optimize the database. We need a rapid response when duplicate msgs happens.~~ -> created a separate [issue](https://github.com/waku-org/nwaku/issues/1842)
- [x] Run the current sqlite unittest set for the postgresql driver.
- ~~[ ] Apply @Menduist 's enhancement suggestions for a more appropriate asynchronous handling: https://github.com/waku-org/nwaku/pull/1631#discussion_r1154267054~~ -> created a separate [issue](https://github.com/waku-org/nwaku/issues/1842)
- ~~[ ] Protect the nwaku compilation process so that the user has the `libpq` library properly installed.~~ -> created a separate [issue](https://github.com/waku-org/nwaku/issues/1839)
- ~~[ ] Create a docker file to bring nwaku + PostgreSQL simultaneously. Ping @LordGhostX when completed.~~ -> created a separate [issue](https://github.com/waku-org/nwaku/issues/1840)

**Comment by Ivansete-status** [comment]
This is Done.
