### ISSUE TITLE
chore(postgres): Optimize the database. 

### ISSUE THREAD

**Issue by Ivansete-status** [waku-org/nwaku#1842]
### Background
When `nwaku` has the "store/archive" protocol mounted it can store and retrieve historical messages. All this information is kept in a single table, `messages`. We need to optimize this.

### Details
We need to get the maximum performance possible with regard to insert/select operations.
We need a rapid response when duplicate msgs happens. For that, we may need to adapt how the message id is generated so that we achieve high selectivity.

### Tasks
- ~[ ] Rename the `messages` table to `MESSAGE`.~ (that renaming caused issues in the current existing `shards.test` fleet.
~~- [ ] Apply @Menduist 's enhancement suggestions for a more appropriate asynchronous handling: https://github.com/waku-org/nwaku/pull/1631#discussion_r1154267054~~
- [x] Perform tests in a standalone database. This is a DB analyst task where operations are checked in a table with hundreds of millions of rows.
- [x] Apply "integration" performance tests. 
:information_source:  We understand that a query performance is acceptable in Grafana by checking that "Waku Archive Query Duration" is <50ms.
:information_source: For that, we will use the next repo: https://github.com/waku-org/test-waku-query (cc - @richard-ramos )

### Related issue
https://github.com/waku-org/nwaku/issues/1604

**Comment by jm-clius** [comment]
- [ ] add an index column with the consistent, deterministic message hash as message ID.

**Comment by Ivansete-status** [comment]
<<Apply "integration" performance tests.>> This is done in the https://github.com/waku-org/test-waku-query repo

**Comment by Ivansete-status** [comment]
I'm reluctant to perform the @Menduist enhancement. We might still have a bottleneck in `while pqIsBusy(db) == 1:` for concurrent _Store_ queries (see TODO comment in https://github.com/waku-org/nwaku/blob/6da1aeec5370bb1c116509e770178cca2662b69c/waku/common/databases/db_postgres/dbconn.nim#L124)

**Comment by Ivansete-status** [comment]
Tests had been performed in the database itself with ~12 million rows. On the other hand, the bottleneck is within the `db.pqisBusy()` as mentioned above. See https://www.notion.so/Postgres-e33d8e64fa204c4b9dcb1514baf9c582

**Comment by Ivansete-status** [comment]
> * [ ]  add an index column with the consistent, deterministic message hash as message ID.

Thanks for adding this point @jm-clius!
I'll check it in this issue because it is properly being tackled in https://github.com/waku-org/nwaku/issues/2112 by @ABresting 
Cheers

**Comment by Ivansete-status** [comment]
We conclude the _Postgres_ optimization for now.
Find more details in https://github.com/waku-org/nwaku/wiki/Adoption-of-Postgres-as-an-archive-system
