### ISSUE TITLE
PostgreSQL

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/nwaku#1888]
**Planned start date**:
**Due date**: 

# Summary

Implementation of PosgreSQL database engine for Waku Store queries.

See https://github.com/waku-org/pm/issues/4 for details.

# Acceptance Criteria

- [x] PostgreSQL is available in nwaku
- [x] Options to easily deploy PosgresSQL with nwaku available (e.g. docker compose)

## Tasks

- [x] https://github.com/waku-org/nwaku/issues/1604
- [x] https://github.com/waku-org/nwaku/issues/1894
- [x] https://github.com/waku-org/nwaku/issues/1840
- [x] https://github.com/waku-org/nwaku/issues/1893
~~- [ ] https://github.com/waku-org/nwaku/issues/1885~~
- [x] https://github.com/waku-org/nwaku/issues/1842
- [x] https://github.com/waku-org/nwaku/issues/1841

# RAID (Risks, Assumptions, Issues and Dependencies)

**Comment by Ivansete-status** [comment]
**Weekly Update**

- _achieved_: Docker compose with `nwaku` + `postgres` + `prometheus` + `grafana` + `postgres_exporter` https://github.com/alrevuelta/nwaku-compose/pull/3
- _next_: Carry on with stress testing

**Comment by fryorcraken** [comment]
I suggest to confirm PostgreSQL integration done, as it is actually done, especially that concurrent requests are already implemented. This should be good enough for 10k users.

We can then move this issue to scope PostgreSQL optimizations for 1mil users target. Do you agree @Ivansete-status ?

**Comment by Ivansete-status** [comment]
> I suggest to confirm PostgreSQL integration done, as it is actually done, especially that concurrent requests are already implemented. This should be good enough for 10k users.
> 
> We can then move this issue to scope PostgreSQL optimizations for 1mil users target. Do you agree @Ivansete-status ?

Morning @fryorcraken ! The PostgreSQL integration is completed but I have a doubt: for 10k users, how many requests per second should we support ? And how many for 1mil? I think we need first to measure the current performance and this task is in progress, implementing a basic stress tests :)

**Comment by fryorcraken** [comment]
@kaiserd did a hackmd that did the estimation for relay scaling which gave us a theoretical green light for 10k users per shard. Maybe we can use the same figures for Store. However, it is challenging to estimate the needs in any case.

An alternative would be to look at the usage of store node in Status prod fleet. It's for ~100 contributors.
We can multiply this by 10x (1000 users) this would give us an idea of needs for 10k users (10 shards, 1000 users per shards). Not the 1mil users is 100 shards, 10k users per shards.

Another alternative would be to stress test sqlite and postgresql and if we demonstrated a 10x improvement then we can reach the same conclusion: we can support 100 users with sqlite, postgresql is 10x more performance, hence in theory we can support 1000 users with PostgreSQL.

SQLite and PostgreSQL are industry standards, surely there are available benchmarks that can tell us this performance difference?

Then, the next step is the needs of 10k users. I believe this is where optimization and DST simulation would be necessary.

> I think we need first to measure the current performance

Indeed, it may make sense to measure performance and confirm there are no issues on nwaku code that bottlenecks the usage of PostgreSQL.
Great to hear it's in progress. where is it trcked?

> implementing a basic stress tests

Is that something to be done with Kurtosis or more simple one? Where is it tracked? is the intent to just run it once or have it part of regular processes (e.g. release candidate).

**Comment by Ivansete-status** [comment]
> SQLite and PostgreSQL are industry standards, surely there are available benchmarks that can tell us this performance difference?
Sure, we can check that. And also compare our current implementations.

The stress test creation is tracked in the next issue. The idea, for now, is to make manual runs and measurements.
https://github.com/waku-org/nwaku/issues/1894

**Comment by jm-clius** [comment]
For now a manual measurement would be a good start IMO. In fact, we can look at current query rate for Status Community and assume a linear increase with increase in numbers and simply script that many queries to a postgresql instance. Very crude estimate with approximate results, but will give us a good initial benchmark.

**Comment by Ivansete-status** [comment]
**Weekly Update**

- _achieved_: Learned that the insertion rate is constrained by the `relay` protocol. i.e. the maximum insert rate is limited by `relay` so I couldn't push the "insert" operation to a limit from a _Postgres_ point of view. For example, if 25 clients publish messages concurrently, and each client publishes 300 msgs, all the messages are correctly stored. If repeating the same operation but with 50 clients, then many messages are lost because the _relay_ protocol doesn't process all of them.
- _next_: Carry on with stress testing. Analyze the performance differences between _Postgres_ and _SQLite_ regarding the _read_ operations.

**Comment by Ivansete-status** [comment]
**Weekly Update**

- _achieved_: new _docker compose_ in `test-waku-query` that allows to quickly compare `insert` and `query` performance between _SQLite_ and _Postgres_.
- _next_: Carry on with stress testing & follow-up of the _Postgres_ addition to [waluv2.shards](https://github.com/status-im/infra-nim-waku/blob/master/ansible/group_vars/wakuv2-shards.yml) by the _infra_ team.

**Comment by Ivansete-status** [comment]
**Weekly Update**

- _achieved_: Download and start configuring `jmeter` to have a variable number of clients sending concurrent _Store_ requests.
- _next_: Carry on with stress testing & follow-up of the _Postgres_ addition to [wakuv2.shards](https://github.com/status-im/infra-nim-waku/blob/master/ansible/group_vars/wakuv2-shards.yml) by the _infra_ team.

**Comment by Ivansete-status** [comment]
**Weekly Update**

- _achieved_:
i. Created a `jmeter` test plan to stress _Store_ queries through REST _Store_. As a conclusion, the node with _Store_ _Postgres_ showed worse performance than the one with _SQLite_.
https://github.com/waku-org/test-waku-query/pull/5
ii. Added reconnection feature. If the connection with _Postgres_ is lost, the `nwaku` node tries to reconnect again. https://github.com/waku-org/nwaku/pull/1997
iii. The `wakuv2.shards` fleet had been de-prioritized in favor of the `status.shards` one.
https://github.com/status-im/infra-nim-waku/issues/74#issuecomment-1710514544

- _next_: Optimize database so that the _Store_ requests behave better with _Postgres_.

**Comment by Ivansete-status** [comment]
Weekly Report Template

**Weekly Update**

- _achieved_: During the stress testing, I discovered that the max throughput seems not to be directly related to _Postgres_. If I make the code to ignore _Postgres_ and return immediately a mocked response, then the throughput is even lower.

- _next_: Carry on with "select" performance analysis and analyze it directly from a _Store_ client, rather than having `REST` <-> `Store_Client` <-> `Store_Server`. By ignoring the `REST` layer we will have a better insight into the actual _Store_ protocol, as @jm-clius recommended to me some time ago.

**Comment by Ivansete-status** [comment]
**Weekly Update**

- _achieved_: Applied performance comparison between _SQLite_ and _Postgres_ but in this case, making direct requests from a  `go-waku` unittest that @richard-ramos had prepared.
After directly comparing the _Store_ protocol, noticed that the bottle neck is within the database itself. i.e. the _SQLite_ database performs better than _Postgres_, given that we have a very simple schema and simple queries, without joins. Adding indexes to the _Postgres_ database didn't help very much. For example, given the same query, _SQLite_ takes 1ms whereas _Postgres_ takes 6ms.

- _next_:
   - Wrap up the _Store_ testing environment and install it into our sandbox machine, `metal-01.he-eu-hel1.wakudev.misc.statusim.net`, so that anyone can proceed from this point (two databases with the same dataset of ~2 million rows .) in case someone is keen on analyzing performance or debug in a more realistic testing scenery.
   - Start extracting the database creation and indexes creation to outside the code base.

**Comment by Ivansete-status** [comment]
**Weekly Update**

- _achieved_:
   - Testing environment prepared in `metal-01.he-eu-hel1.wakudev.misc.statusim.net`. There are two databases (Postgres and SQLite) with 5 million of random messages.
   - Enhanced Grafana dashboard so that we can compare timings performance throughout an histogram ( @alrevuelta's idea .)
  
- _next_: Carry on with the investigation to enhance the _Postgres_ performance.

**Comment by Ivansete-status** [comment]
**Weekly Update**

- _achieved_:
  - Time processing enhancement when performing _SELECT_ operations. There was an overhead caused by looping too many times over the returned rows, in order to convert the row types. By applying a "rowCallback" approach we can reduce in 30ms the time spent on the query under analysis.
- _next_:
  - The queries used in the comparison analysis still perform much better in _SQLite_ (< ~5ms) than in _Postgres_ (< ~15ms.) Therefore we need to push the investigation further to enhance that.

**Comment by Ivansete-status** [comment]
**Weekly Update**

- _achieved_: Optimize _select_/_Store_ queries by adding prepared statements. [PR](https://github.com/waku-org/nwaku/pull/2182)
- _next_: Wrap up the Postgres optimizations. Summarize the performance comparison in a report.

**Comment by Ivansete-status** [comment]
The report was created in https://github.com/waku-org/nwaku/wiki/Postgres-adoption

**Comment by Ivansete-status** [comment]
I crossed out "https://github.com/waku-org/nwaku/issues/1885" from the description list because the "size" retention policy isn't strictly related to Postgres only.

Therefore, this task can be considered complete.
