### ISSUE TITLE
[Epic] Release Process Improvements

### ISSUE THREAD

**Issue by vpavlin** [waku-org/nwaku#1889]
**Planned start date**:
**Due date**:

# Summary

Improve the `nwaku` release process to bring in more automation, reproducibility and additional target architectures and platforms

# Acceptance Criteria

- [ ] Release process is mostly automated with some basic manual steps to fix typos in release notes and manual "approval"
- [ ] Binaries and images for additional architectures and platforms are available as part of the release
- [ ] `nwaku` can be easily tested and simulation be run for each PR and release (i.e. nightly, RC, final) both manually and automatically 

## Tasks

Breakdown of the work

- [ ] #1879 
- [ ] #1877 
- [x] #1873

# RAID (Risks, Assumptions, Issues and Dependencies)

**Comment by vpavlin** [comment]
**Weekly Update**

- _achieved_: fixed but in release CI workflow, enhanced the CI workflow to build and push a docker image on each PR to make simulations per PR more feasible
- _next_: document how to run PR built images in waku-simulator, adding Linux arm64 binaries and images
- _blocker_:

**Comment by vpavlin** [comment]
**Weekly Update**

- _achieved_: minor CI fixes and improvements
- _next_: document how to run PR built images in waku-simulator, adding Linux arm64 binaries and images

**Comment by vpavlin** [comment]
**Weekly Update**

- _achieved_: added a CI job to notify on unexpected config opetion or DB schema changes
- _next_: document how to run PR built images in waku-simulator, adding Linux arm64 binaries and images

**Comment by vpavlin** [comment]
**Weekly Update**

- _achieved_: minor fixes in GH action workflows, building `experimental` (i.e. RLN enabled) image per-PR to simlify RLN testing/simulatiosn
- _next_: document how to run PR built images in waku-simulator, adding Linux arm64 binaries and images

**Comment by vpavlin** [comment]
**Weekly Update**

- _achieved_:  execute js-waku tests from nwaku workflows against PRs, nightly and release candidates
- _next_: adding Linux arm64 binaries and images
