### ISSUE TITLE
feat: Enforce service specific rate limits

### ISSUE THREAD

**Issue by Ivansete-status** [waku-org/nwaku#2032]
### Problem
We are aiming to enforce DoS protection per libp2p services.

In this feature, we consider the limitation applied to the non-_Relay_ protocols (lightpush, peer exchange, store, filter.) because the _Relay_ protocol will benefit from the _RLN_ protection.

### Suggested solution
1. Apply different limits per service (lightpush, peer exchange, store, rendezvous, filter.)
2. Apply one single limit to be followed by all the libp2p protocols

### Additional context
The issue originated from this great proposal: https://github.com/waku-org/go-waku/issues/667

### Acceptance criteria
- [x] Be able to measure which is the normal use of each protocol. Regarding bandwidth and request rate. Then, the limit should be a certain rate higher than the normal or average usage.

### Tasks

- [x] https://github.com/waku-org/nwaku/issues/1809
- [X] https://github.com/waku-org/nwaku/issues/2589
- [x] https://github.com/waku-org/nwaku/issues/2683
- [x] https://github.com/waku-org/nwaku/issues/3028

**Comment by chair28980** [comment]
@NagyZoltanPeter @Ivansete-status does the completion of https://github.com/waku-org/nwaku/issues/1809 cover the acceptance criteria here? Safe to close this issue?

**Comment by NagyZoltanPeter** [comment]
> @NagyZoltanPeter @Ivansete-status does the completion of #1809 cover the acceptance criteria here? Safe to close this issue?

@chair28980 @Ivansete-status : I would not close this one yet.
I'm about to finish phase2 of this. Last week I redesinged a bit the phase1 rate limit implementation in order to be more generic applicable to all non-relay protocols. Will be PR on THU this week. It will address Alvaro's concerns he made on the phase1 and will add bandwidth metrics also.

**Comment by NagyZoltanPeter** [comment]
Rate limiting DOS protection is added to store(v2-v3), lightpush, filter and peer-exchange protocols.
Fully configurable from the cli individually to each protocol.
Protocol metrics support tracking of server and rejected request rates, in-out traffic rates.
Bandwidth usage (in-net/gros, out) per shard over relay metrics and dashboard also included.
Dashboard is deployed.

Last part - peer-exchange DOS protection and full CLI config - will be released with nwaku v0.33.0.

Dashboard metrics of this feature:
![image](https://github.com/user-attachments/assets/3e5f96de-c037-41a0-a3df-351280f07682)
![image](https://github.com/user-attachments/assets/f40a0098-91ba-4c8d-ad5a-09032aec2c4a)
![image](https://github.com/user-attachments/assets/324c6d79-3037-4e12-9556-adfd26ceaa63)
![image](https://github.com/user-attachments/assets/13f32f28-29b0-41f7-baa7-de7a20ce2e8a)
![image](https://github.com/user-attachments/assets/e85fba23-b29a-4abc-ba6c-9671f80af8ea)
