### ISSUE TITLE
PoC: rln-v2 in waku

### ISSUE THREAD

**Issue by rymnc** [waku-org/nwaku#2345]
### Problem

We do not have arbitrary messaging rates with rln in waku, leading to only 1 message per epoch (set to 1 second)

### Suggested solution

We make use of rln-v2 instead of rln-v1, which brings variable messaging rates depending on the user's stake. 

Till we have a viable tokenomics model for rln-v2, we will just proceed with linearly scaling the stake with the messaging rate.

### Sub-issues for incremental changes

- [x] chore(rln-relay): remove websocket from OnchainGroupManager
  - [x] https://github.com/waku-org/nwaku/pull/2364
- [x] #2375
  - [x] https://github.com/waku-org/nwaku/pull/2381 
- [x] #2376
- [x] #2377
  - [x] https://github.com/waku-org/nwaku/pull/2385
- [x] #2378
  - [x] https://github.com/waku-org/nwaku/pull/2385 
  - the rate commitment now has to be calculated within nwaku: `poseidon([id_commitment, user_message_limit])`
- [x] rln-v2: Update command line arguments to rln-keystore-generator, which now accepts a message rate that the user registers themself with
  - [x] https://github.com/waku-org/nwaku/pull/2392 
- [x] #2415
  - [x] https://github.com/waku-org/nwaku/pull/2413
  - Additionally, the node must clear this nonce every epoch
- [x] #2379
- [x] Appropriate nullifierLog struct: https://github.com/waku-org/nwaku/pull/2508 
- [x] #2481

### Additional context

Zerokit release: https://github.com/vacp2p/zerokit/releases/tag/v0.4.1

### Acceptance criteria

- [ ] A user is able to register themself to the rln-v2 membership set and send multiple messages per epoch

**Comment by rymnc** [comment]
cc: @jm-clius @fryorcraken @alrevuelta @kaiserd

**Comment by fryorcraken** [comment]
> We make use of rln-v2 instead of rln-v1, which brings variable messaging rates depending on the user's stake.

> Till we have a viable tokenomics model for rln-v2, we will just proceed with linearly scaling the stake with the messaging rate.

Can you clarify what exact number we could look into?e,g, you lock 1DAI and you get 1000msgs/day, 2DAY you get 2000msgs/day? This is cool.

**Comment by rymnc** [comment]
yes, something along those lines. however, a day is too large of an epoch size to use - consider the calculations below


```
users = 10_000
nullifier_size = 128 bytes (with metadata)
epoch size = 1 day
avg_user_message_limit = 1_000


total storage used = 10_000 * 128 * 1_000 = 1.2 gigabytes (in memory)
```

if the day epoch size is a requirement from waku, we can work on a persistence layer for the nullifier table, but we will raise the hardware requirements for running a node on the network by consequence.
