### ISSUE TITLE
nwaku Bindings

### ISSUE THREAD

**Issue by chair28980** [waku-org/nwaku#2420]
**Planned start date**:
**Due date**:

Milestone: https://github.com/waku-org/pm/issues/121

# Summary
Nwaku epic tracking Rust, NodeJS, Golang bindings work.

Bindings should provide the following functionality ( 🔖 )

DiscV5 + DNS Discovery
RLN Relay and relay
auto sharding and static sharding
Store client (lower priority)

# Acceptance Criteria

## Tasks

- [ ] Migrate waku-node logic from [app.nim](https://github.com/waku-org/nwaku/blob/master/apps/wakunode2/app.nim) to [waku_node.nim](https://github.com/waku-org/nwaku/blob/master/waku/node/waku_node.nim) - This is needed to make sure we will have the same behaviour in both the waku-node app and the libwaku.
  - #2441
  - #2438
  - #2440 
  - https://github.com/waku-org/nwaku/issues/2452
  - https://github.com/waku-org/nwaku/issues/2453
- [ ] Support setting DiscV5 and/or DNS-disc in libwaku
   - https://github.com/waku-org/nwaku/issues/2455 
- [ ] Implement RLN-relay in libwaku
  - https://github.com/waku-org/nwaku/issues/2454
- [ ] Support auto sharding and static sharding in libwaku
   - https://github.com/waku-org/nwaku/issues/2456
- [ ] libwaku node configurable as a store client
   - https://github.com/waku-org/nwaku/issues/2457
- [ ] Integrate the `nwaku-libwaku` library in [waku-rust-bindings](https://github.com/waku-org/waku-rust-bindings)
  - [ ] https://github.com/waku-org/waku-rust-bindings/issues/90
- [ ] Implement :bookmark: in [waku-rust-bindings](https://github.com/waku-org/waku-rust-bindings) + `nwaku`-libwaku
  - [ ] https://github.com/waku-org/waku-rust-bindings/issues/91
  - [ ] https://github.com/waku-org/waku-rust-bindings/issues/92
  - [ ] https://github.com/waku-org/waku-rust-bindings/issues/93
  - [ ] https://github.com/waku-org/waku-rust-bindings/issues/94
  - [ ] https://github.com/waku-org/waku-rust-bindings/issues/53
  - [ ] https://github.com/waku-org/waku-rust-bindings/issues/95
- [ ] Implement :bookmark: in [nodejs-waku](https://github.com/waku-org/nodejs-waku)
  - https://github.com/waku-org/waku-nodejs-bindings/issues/1
  - https://github.com/waku-org/waku-nodejs-bindings/issues/2
  - https://github.com/waku-org/waku-nodejs-bindings/issues/3
  - https://github.com/waku-org/waku-nodejs-bindings/issues/4
- [ ] Integrate the `nwaku-libwaku` library in a  `waku-go-bindings` repository and create a Go API to consume the bindings
- [ ] Investigate and add mobile support to `waku-go-bindings`.
- [ ] Integrate the `waku-go-bindings` with status-go to demonstrate viability of running nwaku in mobile devices
- [ ] https://github.com/waku-org/nwaku/issues/1332

**Comment by chair28980** [comment]
Closing in favor of tracking Epic in pm repo: https://github.com/waku-org/pm/issues/141
