### ISSUE TITLE
chore(rlnv2): tracking issue for changes required for rlnv2 fork

### ISSUE THREAD

**Issue by rymnc** [waku-org/nwaku#2758]
### Background

ref: https://github.com/waku-org/pm/issues/168

### Details

- [ ] Make RLNv2 the default waku RLN, removing feature flag and RLN v1.
- [ ] Make nwaku use the new contract abi to allow eg new sync mechanism + onchain merkle proofs

### Acceptance criteria

- [ ] nwaku can use the new rlnv2 fork and does not rely on rln-v1 anymore.
