### ISSUE TITLE
[Epic: nwaku] Node Bandwidth Management Features

### ISSUE THREAD

**Issue by chair28980** [waku-org/nwaku#3069]
## Tasks

- [x] https://github.com/waku-org/nwaku/issues/1945
- [x] https://github.com/waku-org/nwaku/issues/1946
- [x] https://github.com/waku-org/nwaku/issues/2032
- [x] https://github.com/waku-org/nwaku/issues/3060
- [ ] https://github.com/waku-org/nwaku/issues/1947 [Out of scope - postponed]
