### ISSUE TITLE
[Epic: nwaku] Store v3 - store synchronisation

### ISSUE THREAD

**Issue by chair28980** [waku-org/nwaku#3071]
## Tasks
- [x] https://github.com/waku-org/nwaku/issues/2425
- [x] https://github.com/waku-org/nwaku/issues/3006
- [x] https://github.com/waku-org/nwaku/issues/3007
- [x] https://github.com/waku-org/nwaku/issues/3030
