### ISSUE TITLE
[Epic: nwaku] PostgreSQL Maintenance

### ISSUE THREAD

**Issue by chair28980** [waku-org/nwaku#3072]
Milestone-issue: https://github.com/waku-org/pm/issues/119

# Tasks
- [x] https://github.com/waku-org/nwaku/issues/1885
- [x] https://github.com/waku-org/nwaku/issues/2689
- [x] https://github.com/waku-org/nwaku/issues/2783 
- [x] https://github.com/waku-org/nwaku/issues/2807
- [x] https://github.com/waku-org/nwaku/issues/2838
- [x] https://github.com/waku-org/nwaku/issues/2869
- [x] https://github.com/waku-org/nwaku/issues/2890
- [x] https://github.com/waku-org/nwaku/issues/2902
- [x] https://github.com/waku-org/nwaku/issues/2895
- [x] https://github.com/status-im/infra-status/pull/37
- [x] https://github.com/waku-org/nwaku/pull/2986
- [x] https://github.com/waku-org/nwaku/issues/2963
- [x] https://github.com/waku-org/nwaku/issues/2995
- [x] https://github.com/waku-org/nwaku/pull/3061

**Comment by Ivansete-status** [comment]
This can be considered completed as all the underlying issues are completed
