### ISSUE TITLE
[Epic: nwaku] Sharding peer management and discovery hardening

### ISSUE THREAD

**Issue by chair28980** [waku-org/nwaku#3073]
## Tasks

- [x] https://github.com/waku-org/nwaku/pull/2831
- [x] https://github.com/waku-org/nwaku/issues/2910
- [x] https://github.com/waku-org/nwaku/issues/2905
- [x] https://github.com/waku-org/nwaku/issues/2892
- [x] https://github.com/waku-org/nwaku/issues/2877
- [x] https://github.com/waku-org/nwaku/issues/2592

**Comment by Ivansete-status** [comment]
This can now be closed as per @chair28980 's recommendation to move the following bug to a maintenance deliverable: https://github.com/waku-org/nwaku/issues/2594
