### ISSUE TITLE
[Epic: nwaku] add nwaku into status-go

### ISSUE THREAD

**Issue by Ivansete-status** [waku-org/nwaku#3076]
# Summary
https://github.com/status-im/status-go should operate with waku through nwaku

We need to add a new `nwaku` submodule within `status-go` and adapt the current `status-go` code base plus nwaku-libwaku so that we can have  `status-go` working with `nwaku`.

There will be changes in:
- status-go to integrate nwaku
- nwaku to extend libwaku with the features needed by status-go

# Tasks

- [ ] https://github.com/waku-org/nwaku/issues/3039
- [ ] https://github.com/waku-org/nwaku/issues/3052
- [ ] https://github.com/waku-org/nwaku/issues/3053

**Comment by gabrielmer** [comment]
Discv5 works after being disconnected for a long time - the bootstrap nodes are never removed from the routing tables. We can see the code [here](https://github.com/status-im/nim-eth/blob/88e4be4dc40e044834dca68f8b69d144744bf145/eth/p2p/discoveryv5/protocol.nim#L488-L4950)

However, after being online again, we don't attempt to connect to the nodes we already found because we have them in backoff period. When we are disconnected, our node thinks the other nodes are faulty because it can't connect to them, but in fact the faulty node is ours. When online again, because of this issue, our node doesn't attempt to connect to them.

We should create a mechanism to recognize when our node is offline and avoid attempting to connect to other nodes whenever that's the case, or at least avoid mischaracterizing well-behaved peers
