### ISSUE TITLE
Upstream issues

### ISSUE THREAD

**Issue by oskarth** [waku-org/nwaku#658]
*NOTE: This issue belongs in a more general-purpose repo, might move it later*

# Context

Next week we are going to have a refactor week https://github.com/status-im/nim-waku/issues/639

As part of this, we also want to take the time to think about and do some upstream tasks. These are things we don't prioritize day to day, such as libp2p specs, nim repos, etc. Basically giving back and looking beyond our bubble.

# Areas

Non-exhaustive list:

1. Code: Nim-related repos (nim-libp2p, nim-stew, etc)
2. Code: JS/libp2p related repos
3. Specs: libp2p
4. Forum: ethresear.ch and similar
5. Reading list/homework: ethresearch, ethereum magicians, libp2p forum, privacy tools, zcash forum - read and engage as relevant

## Task list

- [ ] Upstream RLN to libp2p specs
- [ ] Upstream privacy analysis to libp2p specs
- [ ] Upstream nim-libp2p issues
- [ ] Upstream js-libp2p issues
- [ ] Upstream random utils to nim-stew
- [ ] Reply/create discussions on ethresear.ch/ethereum magicians where discussion is happening about Whisper/messaging stuff
- [ ] List nim-libp2p on libp2p
- [ ] nim-web3 operations needed for SWAP (https://github.com/status-im/nim-web3/issues/33 and similar)

**Comment by oskarth** [comment]
^ @staheri14 @jm-clius @D4nte @EbubeUd for ideas

**Comment by D4nte** [comment]
on js-libp2p side:
- review connection mgmt with chainsafe team
- Some PR already merged regarding wss

**Comment by oskarth** [comment]
Also see https://github.com/vacp2p/rfc/issues/168
