### ISSUE TITLE
Laundry list of `nwaku` refactoring tasks

### ISSUE THREAD

**Issue by jm-clius** [waku-org/nwaku#688]
### Background

Many high priority refactor tasks were completed as part of the [`nim-waku` refactor week](https://github.com/status-im/nim-waku/issues/639) that ran between 12 and 16 July.

This issue collects the outstanding refactor tasks which can be tackled in an ad-hoc manner or in another focused effort, as was done during refactor week.

Note that the best guide to refactoring remains the [Nim style guide](https://status-im.github.io/nim-style-guide/00_introduction.html).

Checklist for general refactoring of each module [here](https://hackmd.io/1imOGULZRsed2HpgmzGleA).
Overview of all tasks [here](https://hackmd.io/beMbu_fdRymYvaXDANukIw)

### Outstanding issues

- [ ] Add `-d:chronosStrictException` compiler directive for all MAKE targets.
- [ ] **Clean up APIs** (`Nim` and `JSON-RPC`): e.g. users of each API should be forced to set a `contentTopic` and be unable to modify the `WakuMessage` `timestamp` when publishing (may also cover https://github.com/status-im/nim-waku/issues/582).
- [ ] [**Clean up parameter initialisation**](https://github.com/status-im/nim-waku/issues/562), especially for `WakuRelay`
- [ ] [**Simplify pagination logic**](https://github.com/status-im/nim-waku/issues/484)
- [ ] [**Use of `requestId`**](https://github.com/status-im/nim-waku/issues/257) confusing. Can probably be improved.
- [ ] Add **readme file to explain `nim-waku` structure**
- [ ] **Unittest style guide** (also refactoring of existing tests?)
- [ ] CI improvements, e.g. https://github.com/status-im/nim-waku/issues/391. Also see if CI logging can be improved.
- [ ] [**External dependency clean-up/documentation**](https://github.com/status-im/nim-waku/issues/341)

**Comment by arnetheduck** [comment]
[ ] - open issues in the nim style guide repo about things that have better solutions, were pain points or could be clarified

**Comment by jm-clius** [comment]
Most of these tasks since addressed or being tracked in other efforts.
